/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [Facility ID]
      ,[Facility Name]
      ,[Address]
      ,[City]
      ,[State]
      ,[ZIP Code]
      ,[County Name]
      ,[Phone Number]
      ,[Condition]
      ,[Measure ID]
      ,[Measure Name]
      ,[Score]
      ,[Sample]
      ,[Footnote]
      ,[Start Date]
      ,[End Date]
  FROM [Timely and Effective].[dbo].['Timely_and_Effective_Care-Hospi$']
  where Condition like '%emergency%' and [Measure Name] not like '%head%'