  SELECT [Facility ID]
      ,[Facility Name]
      ,[City]
      ,[State]
      ,[Condition]
      ,[Measure Name]
      ,[Score]
      ,[Sample]
  FROM [Timely and Effective].[dbo].['Timely_and_Effective_Care-Hospi$']
